In [182]:
import pandas as pd
from keras import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder, StandardScaler
import numpy as np

In [183]:
df = pd.read_csv("soybean.csv")
df

date plant-stand   precip     temp  ... seed-size shriveling   roots                  class
0    october      normal  gt-norm     norm  ...      norm     absent    norm  diaporthe-stem-canker
1     august      normal  gt-norm     norm  ...      norm     absent    norm  diaporthe-stem-canker
2       july      normal  gt-norm     norm  ...      norm     absent    norm  diaporthe-stem-canker
3       july      normal  gt-norm     norm  ...      norm     absent    norm  diaporthe-stem-canker
4    october      normal  gt-norm     norm  ...      norm     absent    norm  diaporthe-stem-canker
..       ...         ...      ...      ...  ...       ...        ...     ...                    ...
678    april           ?        ?        ?  ...         ?          ?       ?           2-4-d-injury
679    april   lt-normal        ?  lt-norm  ...         ?          ?  rotted       herbicide-injury
680     june   lt-normal        ?  lt-norm  ...         ?          ?  rotted       herbicide-injury
681    april   lt-normal        ?  lt-norm  ...         ?          ?  rotted       herbicide-injury
682     june   lt-normal        ?  lt-norm  ...         ?          ?  rotted       herbicide-injury

[683 rows x 36 columns]

In [185]:
df["precip"].value_counts()

gt-norm    459
norm       112
lt-norm     74
?           38
Name: precip, dtype: int64

In [168]:
X = df.iloc[:, 0:len(df.columns) - 1].values
Y = df["class"].values

In [169]:
encoder = LabelEncoder()
Y = encoder.fit_transform(Y)
Y

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10,  7,  7,  7,  7,  7,  7,  7,
        7,  7,  7, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 15, 15, 15, 15,
       15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
       15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
       15, 15,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  6, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 11, 11,
       11, 11, 11, 11, 11, 11, 11, 11,  5,  5,  5,  5,  5,  5,  5,  5,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
       17, 17, 17, 17, 17, 17, 17, 17, 17, 17,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2, 14, 14, 14, 14,
       14, 14, 14, 14, 14, 14,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1

In [170]:
_, columns_X = pd.DataFrame(X).shape
columns_X

35

In [171]:
for i in range(columns_X):
    X[:,i] = encoder.fit_transform(X[:,i])

X

array([[6, 2, 1, ..., 2, 1, 2],
       [2, 2, 1, ..., 2, 1, 2],
       [3, 2, 1, ..., 2, 1, 2],
       ...,
       [4, 1, 0, ..., 0, 0, 3],
       [1, 1, 0, ..., 0, 0, 3],
       [4, 1, 0, ..., 0, 0, 3]], dtype=object)

In [172]:
X

array([[6, 2, 1, ..., 2, 1, 2],
       [2, 2, 1, ..., 2, 1, 2],
       [3, 2, 1, ..., 2, 1, 2],
       ...,
       [4, 1, 0, ..., 0, 0, 3],
       [1, 1, 0, ..., 0, 0, 3],
       [4, 1, 0, ..., 0, 0, 3]], dtype=object)

In [173]:
targets = len(df["class"].unique())

In [174]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, random_state = 42, train_size = 0.75)

In [175]:
X_train

array([[7, 2, 1, ..., 2, 1, 2],
       [7, 2, 2, ..., 2, 1, 2],
       [5, 2, 1, ..., 2, 1, 2],
       ...,
       [3, 2, 1, ..., 2, 1, 2],
       [4, 2, 1, ..., 2, 1, 2],
       [5, 2, 1, ..., 2, 1, 2]], dtype=object)

In [176]:
stdScale = StandardScaler()
X_train = stdScale.fit_transform(X_train)
X_test = stdScale.fit_transform(X_test)

In [181]:
model = Sequential()

# Criando os Hidden layers
model.add(Dense(units = 48, input_dim = 35, activation="relu"))
model.add(Dense(units = 37, activation="relu"))
model.add(Dense(units = targets, activation = "softmax"))

model.compile(optimizer="adam", loss='categorical_crossentropy', metrics = ["accuracy"])
model.fit(X_train, y_train, epochs=100, batch_size=12)

Epoch 1/100


ValueError: ignored