In [68]:
# !pip install -U scikit-fuzzy
#Instalar o skfuzzy

In [69]:
from sklearn import datasets
import numpy as np
from sklearn.metrics import confusion_matrix
import skfuzzy
import pandas as pd

In [70]:
iris = datasets.load_iris()
pd.DataFrame(iris.data.T)

0    1    2    3    4    5    6    7    8    9    ...  140  141  142  143  \
0  5.1  4.9  4.7  4.6  5.0  5.4  4.6  5.0  4.4  4.9  ...  6.7  6.9  5.8  6.8   
1  3.5  3.0  3.2  3.1  3.6  3.9  3.4  3.4  2.9  3.1  ...  3.1  3.1  2.7  3.2   
2  1.4  1.4  1.3  1.5  1.4  1.7  1.4  1.5  1.4  1.5  ...  5.6  5.1  5.1  5.9   
3  0.2  0.2  0.2  0.2  0.2  0.4  0.3  0.2  0.2  0.1  ...  2.4  2.3  1.9  2.3   

   144  145  146  147  148  149  
0  6.7  6.7  6.3  6.5  6.2  5.9  
1  3.3  3.0  2.5  3.0  3.4  3.0  
2  5.7  5.2  5.0  5.2  5.4  5.1  
3  2.5  2.3  1.9  2.0  2.3  1.8  

[4 rows x 150 columns]

In [71]:
'''
    data => dados que iremos usar

    C => Número de cluster's

    M => Exponenciação de cada interação

    error => Tolerância de erro

    maxiter => Número máximo de iterações

    init => Começando o algorítmos aleátoriamente
'''
r = skfuzzy.cmeans(data = iris.data.T, c=3, m = 2, error=0.005, maxiter=1000, init = None)

In [72]:
#Obtendo as porcentagens de um registro pertencente a um cluster que está na posição 1
previsoes_porcentagem = r[1]

In [73]:
previsoes_porcentagem

array([[2.30444610e-03, 1.66605475e-02, 1.37667091e-02, 2.24796895e-02,
        3.76210718e-03, 4.48292850e-02, 1.40112755e-02, 3.11731769e-04,
        4.77457894e-02, 1.19437919e-02, 2.17669057e-02, 5.43586345e-03,
        2.01952262e-02, 5.18191898e-02, 7.26347754e-02, 1.04383961e-01,
        3.55931805e-02, 2.28888588e-03, 6.55889837e-02, 1.41633668e-02,
        2.18703098e-02, 1.03782298e-02, 2.75190482e-02, 1.44743324e-02,
        2.32611167e-02, 1.84731446e-02, 3.58520117e-03, 4.56719750e-03,
        4.32978777e-03, 1.42116382e-02, 1.48103157e-02, 1.77071244e-02,
        4.11612386e-02, 6.35044336e-02, 1.03484883e-02, 1.02056165e-02,
        2.42620973e-02, 6.18391964e-03, 4.11059384e-02, 1.17845105e-03,
        3.58428863e-03, 1.02325959e-01, 3.21931061e-02, 1.43930984e-02,
        3.81523624e-02, 1.92350179e-02, 1.58494824e-02, 1.76625804e-02,
        1.55270452e-02, 2.00907451e-03, 4.53672439e-01, 7.63383997e-01,
        3.68034739e-01, 8.70430497e-01, 7.57974578e-01, 9.737929

In [ ]:
for x in range(150):
    print(previsoes_porcentagem[0][x], previsoes_porcentagem[1][x], previsoes_porcentagem[2][x])

In [75]:
previsoes_argmax = previsoes_porcentagem.argmax(axis = 0)
previsoes_argmax

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0])

In [76]:
previsoes = previsoes_porcentagem.argmax(axis=0)
resultados = confusion_matrix(iris.target, previsoes)
resultados

array([[ 0,  0, 50],
       [47,  3,  0],
       [13, 37,  0]])

In [77]:
re2 = r[2]
for i in range(150):
    print(previsoes_porcentagem[0][x], previsoes_porcentagem[1][x], previsoes_porcentagem[2][x])

0.5807923366209814 0.39227686454853655 0.026930798830482047
0.5807923366209814 0.39227686454853655 0.026930798830482047
0.5807923366209814 0.39227686454853655 0.026930798830482047
0.5807923366209814 0.39227686454853655 0.026930798830482047
0.5807923366209814 0.39227686454853655 0.026930798830482047
0.5807923366209814 0.39227686454853655 0.026930798830482047
0.5807923366209814 0.39227686454853655 0.026930798830482047
0.5807923366209814 0.39227686454853655 0.026930798830482047
0.5807923366209814 0.39227686454853655 0.026930798830482047
0.5807923366209814 0.39227686454853655 0.026930798830482047
0.5807923366209814 0.39227686454853655 0.026930798830482047
0.5807923366209814 0.39227686454853655 0.026930798830482047
0.5807923366209814 0.39227686454853655 0.026930798830482047
0.5807923366209814 0.39227686454853655 0.026930798830482047
0.5807923366209814 0.39227686454853655 0.026930798830482047
0.5807923366209814 0.39227686454853655 0.026930798830482047
0.5807923366209814 0.39227686454853655 0